[features]
seeds = false
skip-lint = false
[programs.devnet]
nft_social_media = "7Y8TMYmwvJEPQPUJ33uhH1Y44XPoKi93EQRgtZrtAcs9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/yanaemons/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
